CREATE OR REPLACE FUNCTION public.alta_modifica_ficha_medica_conemisiones_temporales()
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$DECLARE
  respuesta BOOLEAN;
  
  

BEGIN

respuesta = true;

CREATE TEMP TABLE TEMPFICHAMEDICAINFO ( IDFICHAMEDICA INTEGER,FMTFECHAINICIO DATE, IDCENTROFICHAMEDICA INTEGER
									   , IDCENTROFICHAMEDICAINFO INTEGER, IDFICHAMEDICAINFO INTEGER,IDPASEINFODOCUMENTO BIGINT
									   ,IDCENTROPASEINFODOCUMENTO INTEGER,FMIFECHA DATE, FMIMFECHAFIN DATE, FMIAUDITOR INTEGER
									   , USUARIOLOGUEADO INTEGER, FMIDESCRIPCION CHARACTER VARYING, NRODOC VARCHAR, TIPODOC INTEGER
									   , FMFECHACREACION DATE, FMDESCRIPCION  CHARACTER VARYING,IDAUDITORIATIPO INTEGER
									   , IDCENTROFICHAMEDICATRATAMIENTO INTEGER, IDFICHAMEDICATRATAMIENTO INTEGER
									   ,IDFICHAMEDICATRATAMIENTOTIPO INTEGER,IDFICHAMEDICAINFOTIPOS INTEGER,ELIMINAR BOOLEAN
									   ,IDFICHAMEDICAINFOMEDICAMENTO BIGINT,IDCENTROFICHAMEDICAINFOMEDICAMENTO INTEGER,IDPASEORIGEN INTEGER
									   , IDCENTROPASEORIGEN INTEGER, IDPASEDESTINO INTEGER, IDCENTROPASEDESTINO INTEGER, FMIDFECHAINGRESO DATE
									   , FMIDOBSERVACION VARCHAR, IDPERSONAORIGEN BIGINT, IDPERSONADESTINO BIGINT, IDPLANCOBERTURAS BIGINT
									   , IDARTICULO BIGINT, IDCENTROARTICULO INTEGER, IDMONODROGA INTEGER, FMIMCOBERTURA FLOAT
									   , FMIMDOSISDIARIA VARCHAR, FMIMMPRESENTACION VARCHAR, IDSOLICITUDAUDITORIAITEM BIGINT
									   , IDCENTROSOLICITUDAUDITORIAITEM INTEGER, INFOMEDICAMENTOS BOOLEAN,ACOBSERVACIONEXPENDIO VARCHAR
									   ,  ACOBSERVACIONAUDITORIA VARCHAR, ACIDPLANCOBERTURAS CHARACTER VARYING DEFAULT '**'::CHARACTER VARYING
									   , SEAUDITA BOOLEAN, SEREPITE BOOLEAN, PRIORIDAD INTEGER, PERIODO VARCHAR,  CANTIDADTOTAL INTEGER
									   ,  CANTIDADXPERIODO INTEGER, GENERARPENDIENTES VARCHAR , SAEOBSERVACION VARCHAR  );


return respuesta;
END;
$function$
