CREATE OR REPLACE FUNCTION public.insertarccprestador(fila prestador)
 RETURNS prestador
 LANGUAGE plpgsql
AS $function$
    BEGIN
    fila.prestadorcc:= current_timestamp;
    UPDATE sincro.prestador SET diaspago= fila.diaspago, gln= fila.gln, idcentrodomiciliolegal= fila.idcentrodomiciliolegal, idcentrodomicilioreal= fila.idcentrodomicilioreal, idcolegio= fila.idcolegio, idcondicioncompra= fila.idcondicioncompra, idcondicioniva= fila.idcondicioniva, iddomiciliolegal= fila.iddomiciliolegal, iddomicilioreal= fila.iddomicilioreal, idprestador= fila.idprestador, idtiporetencion= fila.idtiporetencion, nrocuentac= fila.nrocuentac, pagenteganancias= fila.pagenteganancias, pagenteiibb= fila.pagenteiibb, pagenteiva= fila.pagenteiva, pcategoria= fila.pcategoria, pcbu= fila.pcbu, pcontacto= fila.pcontacto, pctabancaria= fila.pctabancaria, pcuit= fila.pcuit, pdescripcion= fila.pdescripcion, pdireccion= fila.pdireccion, pdomiciliolegal= fila.pdomiciliolegal, pemail= fila.pemail, pesagrupador= fila.pesagrupador, pfax= fila.pfax, pfechavtornp= fila.pfechavtornp, pgast= fila.pgast, piva= fila.piva, pmerc= fila.pmerc, pnombrefantasia= fila.pnombrefantasia, pnroiibb= fila.pnroiibb, pnroregpretadores= fila.pnroregpretadores, pobservacion= fila.pobservacion, prestadorcc= fila.prestadorcc, pseguro= fila.pseguro, ptelefono= fila.ptelefono, ptelefonomovil= fila.ptelefonomovil, pvtopoliza= fila.pvtopoliza, pwww= fila.pwww WHERE idprestador= fila.idprestador AND TRUE;
    IF NOT FOUND THEN
		INSERT INTO sincro.prestador(diaspago, gln, idcentrodomiciliolegal, idcentrodomicilioreal, idcolegio, idcondicioncompra, idcondicioniva, iddomiciliolegal, iddomicilioreal, idprestador, idtiporetencion, nrocuentac, pagenteganancias, pagenteiibb, pagenteiva, pcategoria, pcbu, pcontacto, pctabancaria, pcuit, pdescripcion, pdireccion, pdomiciliolegal, pemail, pesagrupador, pfax, pfechavtornp, pgast, piva, pmerc, pnombrefantasia, pnroiibb, pnroregpretadores, pobservacion, prestadorcc, pseguro, ptelefono, ptelefonomovil, pvtopoliza, pwww) VALUES (fila.diaspago, fila.gln, fila.idcentrodomiciliolegal, fila.idcentrodomicilioreal, fila.idcolegio, fila.idcondicioncompra, fila.idcondicioniva, fila.iddomiciliolegal, fila.iddomicilioreal, fila.idprestador, fila.idtiporetencion, fila.nrocuentac, fila.pagenteganancias, fila.pagenteiibb, fila.pagenteiva, fila.pcategoria, fila.pcbu, fila.pcontacto, fila.pctabancaria, fila.pcuit, fila.pdescripcion, fila.pdireccion, fila.pdomiciliolegal, fila.pemail, fila.pesagrupador, fila.pfax, fila.pfechavtornp, fila.pgast, fila.piva, fila.pmerc, fila.pnombrefantasia, fila.pnroiibb, fila.pnroregpretadores, fila.pobservacion, fila.prestadorcc, fila.pseguro, fila.ptelefono, fila.ptelefonomovil, fila.pvtopoliza, fila.pwww);
    END IF;
    RETURN fila;
    END;
    $function$
